---
title: "league of legend prediction"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(readr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

# data cleaning


## read the leagueoflegends.csv

```{r}
leagueoflegends = 
  read_csv(file = "./data/LeagueofLegends.csv") %>% 
  janitor::clean_names()
```


## read and clean the tower data

```{r}
tower = 
  read_csv(file = "./data/structures.csv") %>% 
  janitor::clean_names() %>% 
  filter(team == "bTowers", type == "OUTER_TURRET") %>% 
  mutate(
    address = str_remove(address, "http://matchhistory.na.leagueoflegends.com/en/#match-details/TRLH1/")
  )
```

calculate the mean time, group by match id

```{r}
tower = 
  tower %>% 
  group_by(address) %>% 
  mutate(
    outer_tower = mean(time, na.rm = TRUE)
  ) %>% 
  pivot_wider(
    names_from = lane,
    values_from = time
  )
```

join with the overall dataset

```{r}
merge_file = 
  leagueoflegends %>% 
  mutate(address = str_remove(address, "http://matchhistory.na.leagueoflegends.com/en/#match-details/TRLH1/")) %>% 
  select(address, b_result) %>% 
  left_join(leagueoflegends, tower, by = "address") %>% 
  mutate(b_result = recode_factor(b_result, "1" = "win", "0" = "lose"))
```

some visualizations

```{r}
merge_file %>% 
  ggplot(aes(x = b_result, y = outer_tower)) + 
  geom_boxplot()
```


## read and clean the gold data

```{r}
gold = 
  read_csv(file = "./data/gold.csv") %>% 
  janitor::clean_names() %>% 
  filter(type == "golddiff") %>% 
  mutate(
    address = str_remove(address, "http://matchhistory.na.leagueoflegends.com/en/#match-details/TRLH1/")
  ) %>% 
  pivot_longer(
  min_1:min_95,
  names_to = "min", 
  names_prefix = "min_",
  values_to = "gold") %>% 
  drop_na()

gold_ave =
  gold %>% 
  group_by(address) %>% 
  summarize(
    golddiff_mean = mean(gold)
  )
```

combine

```{r}
gold_mg = 
  leagueoflegends %>% 
  mutate(address = str_remove(address, "http://matchhistory.na.leagueoflegends.com/en/#match-details/TRLH1/")) %>% 
  select(address, b_result) %>% 
  left_join(leagueoflegends, gold_ave, by = "address") %>% 
  mutate(b_result = recode_factor(b_result, "1" = "win", "0" = "lose"))
```

Plot

```{r}
gold_mg %>% 
  ggplot(aes(x = b_result, y = golddiff_mean)) + 
  geom_boxplot()
```


## read and clean the neutral kills data

```{r}
monster = read_csv("./data/monsters.csv")
str(monster)
summary(monster)
monster = monster %>% 
  filter(Team %in% c("bDragons", "bBarons", "bHeralds")) %>% 
  group_by(Address, Type) %>% 
  summarize(number = n()) %>% 
  pivot_wider(
    names_from = Type,
    values_from = number
  ) 
monster[is.na(monster)] = 0
monster = monster %>% 
  janitor::clean_names()
```


## read and clean the kills data

```{r}

```




