---
title: "Model"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
library(tidyverse)
library(readr)
library(scales)
library("Hmisc")

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
merge_file = read_csv("./data/merge.csv")
merge_file =
  merge_file %>% 
  mutate(
    b_result = recode_factor(b_result, "lose" = "0", "win" = "1"),
    kill_diff = diff,
    golddiff_mean = golddiff_mean/100
  ) %>% 
  select(-diff)

final_log = merge_file %>% 
  mutate(b_result = factor(b_result)) %>% 
  glm(formula =  b_result ~ golddiff_mean + BARON_NASHOR + DRAGON + AIR_DRAGON + EARTH_DRAGON + WATER_DRAGON + FIRE_DRAGON +golddiff_mean:BARON_NASHOR, family = "binomial")
 
final_log %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)
```

```{r}
my_data =
  merge_file %>% 
  filter(year != 2014) %>% 
  #select(-address, -year, -b_result, -bKills, -rKills, -bTowers, -rTowers) %>% #
  select(outer_mean_diff, golddiff_mean, kill_diff, BARON_NASHOR, AIR_DRAGON, FIRE_DRAGON) %>%
  rename(
    tower = "outer_mean_diff",
    gold = "golddiff_mean",
    kill ="kill_diff",
    nashor = "BARON_NASHOR",
    air = "AIR_DRAGON",
    fire = "FIRE_DRAGON"
  ) %>% 
  drop_na()

res <- cor(my_data)
round(res, 3) %>% 
  knitr::kable()
```

