---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(tidyverse)
library(viridis)
library(plotly)
library(scales)
library(ggridges)
library(patchwork)
```


```{r}
# data cleaning
merge = 
  read_csv(file = "./data/merge.csv") %>% 
  janitor::clean_names() %>% 
  filter(year != 2014) %>% 
  mutate(
    year = recode_factor(year, "2015" = "S5", "2016" = "S6", "2017" = "S7", "2018" = "S8"), 
    year = fct_relevel(year, "S5", "S6", "S7", "S8")
  )

origin_df = 
  read_csv("./data/LeagueofLegends.csv") %>% 
  janitor::clean_names() %>% 
  filter(year != 2014) %>% 
  mutate(
    year = recode_factor(year, "2015" = "S5", "2016" = "S6", "2017" = "S7", "2018" = "S8"), 
    year = fct_relevel(year, "S5", "S6", "S7", "S8")
  )

match_df = 
  read_csv("./data/matchinfo.csv") %>% 
  janitor::clean_names() %>% 
  filter(year != 2014) %>% 
  mutate(
    year = recode_factor(year, "2015" = "S5", "2016" = "S6", "2017" = "S7", "2018" = "S8"), 
    year = fct_relevel(year, "S5", "S6", "S7", "S8"),
    address = str_remove(address,
                         "http://matchhistory.na.leagueoflegends.com/en/#match-details/TRLH1/")
  )

bans = 
  read_csv("./data/bans.csv") %>% 
  janitor::clean_names() %>% 
  mutate(address = 
    str_remove(address,"http://matchhistory.na.leagueoflegends.com/en/#match-details/TRLH1/")) %>% 
  pivot_longer(ban_1:ban_5,
               names_to = "bannumber",
               values_to = "champ_name") %>% 
  drop_na(champ_name)
year_col = merge %>% select(address,year)
bans = 
  left_join(bans,year_col,by = "address") %>% 
  filter(year != 2014) %>% 
  mutate(
    year = recode_factor(year, "2015" = "S5", "2016" = "S6", "2017" = "S7", "2018" = "S8"), 
    year = fct_relevel(year, "S5", "S6", "S7", "S8"))
  

# rsconnect::deployApp('/Users/xingchen/Desktop/Data Science/final_project/final_project.github.io/shiny')
```

Champions BPW
==============================

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
# selectInput widget, something like a dropdown menu
year = 
  origin_df %>% 
  distinct(year) %>% 
  pull()

selectInput(
  "year_choice", 
  label = h3("Select year"),
  choices = year, 
  selected = "S8"
)

# radioButtons widget
position = 
  match_df %>% 
  select(year, starts_with("blue_")) %>% 
  pivot_longer(
    cols =  c(blue_top_champ, blue_jungle_champ, blue_middle_champ, 
              blue_adc_champ, blue_support_champ),
    names_to = "champ_types",
    values_to = "champ_names",
    names_prefix = "blue_"
  ) %>% 
  mutate(champ_types = str_remove(champ_types, "_champ")) %>% 
  distinct(champ_types) %>% pull()
  
radioButtons(
  "position_choice", 
  label = h3("select position"),
  choices = position, selected = "adc")

# widget for bans
team_ban = bans %>% distinct(team) %>% pull()

radioButtons(
  "team_choice",
  label = h3("team select (for ban rate only)"),
  choices = team_ban, selected = "blueBans"
)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Champion's ban rate

```{r}
renderPlotly({
  bans %>% 
  filter(year == input[["year_choice"]], team == input[["team_choice"]]) %>% 
  mutate(champ_name = factor(champ_name),
         totalgame = dim(.)[1]) %>% 
  group_by(champ_name) %>% 
  mutate(totalban = n(),
         banrate = totalban / totalgame) %>% 
  ungroup(champ_name) %>% 
  mutate(champ_name = forcats::fct_reorder(champ_name,banrate)) %>% 
  ggplot(aes(x = champ_name,y = banrate,fill = champ_name)) +
  geom_bar(stat = "identity") +
  theme(axis.text = element_text(size = 5)) +
  coord_flip() +
  viridis::scale_fill_viridis(discrete = TRUE)
})
```

Column {data-width=500}
-----------------------------------------------------------------------

### Champions' Win Rate

```{r}
renderPlotly({
  match_df %>% 
    select(address,year,b_result,blue_top_champ,blue_jungle_champ,
           blue_middle_champ,blue_adc_champ,blue_support_champ) %>% 
    pivot_longer(
      blue_top_champ:blue_support_champ,
      names_to = "champ_position",
      values_to = "champ_name", 
      names_prefix = "blue_") %>% 
    mutate(champ_position = str_remove(champ_position, "_champ")) %>% 
    filter(year == input[["year_choice"]],champ_position == input[["position_choice"]]) %>% 
    mutate(hero_name = as.factor(champ_name)) %>% 
    group_by(hero_name) %>% 
    mutate(total = n()) %>% 
    filter(b_result == 1) %>% 
    mutate(nwin = n(),
           win_rate = nwin/total) %>% 
    ungroup(hero_name) %>% 
    mutate(
      hero_name = forcats::fct_reorder(hero_name,win_rate,.desc = FALSE)) %>% 
    ggplot(aes(x = hero_name,y = win_rate,fill = hero_name)) +
    geom_bar(stat = "identity") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.title = element_text(size = 20),
          axis.text = element_text(size = 10)) +
    viridis::scale_fill_viridis(discrete = TRUE) +
    labs(
      x = "",
      y = "win rate")
})
```

### Champion's pick rate

```{r}
renderPlotly({
  match_df %>% 
  select(
    address,year,blue_top_champ,blue_middle_champ,blue_jungle_champ,
    blue_adc_champ,blue_support_champ,red_top_champ,red_middle_champ,
    red_jungle_champ,red_adc_champ,red_support_champ) %>% 
  pivot_longer(
    blue_top_champ:red_support_champ,
    names_to = "champ_position",
    values_to = "champ_name",
    names_prefix = "blue_") %>% 
  mutate(champ_position = str_remove(champ_position, "_champ")) %>% 
  filter(year == input[["year_choice"]],champ_position == input[["position_choice"]]) %>% 
  mutate(
    champ_name = factor(champ_name),
    totalgame = dim(.)[1]
  ) %>% 
  group_by(champ_name) %>% 
  mutate(totalpick = n(),
         pickrate = totalpick/totalgame) %>% 
  ungroup(champ_name) %>% 
  mutate(champ_name = forcats::fct_reorder(champ_name,pickrate)) %>% 
  ggplot(aes(x = champ_name,y = pickrate,fill = champ_name)) +
  geom_bar(stat = "identity") +
  theme(axis.text = element_text(size = 5)) +
  coord_flip() +
  viridis::scale_fill_viridis(discrete = TRUE)
})
```


Winning rate simulator
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
# sliderInput widget of gold diff
min_gold_diff = -9000
max_gold_diff = 9000

sliderInput(
  "gold_range", 
  label = h3("Gold difference"), 
  min = min_gold_diff, max = max_gold_diff, value = 0)

# sliderInput widget of baron nashor
min_baron_nashor = 0
max_baron_nashor = merge %>% drop_na(baron_nashor) %>% distinct(baron_nashor) %>% max()

sliderInput(
  "baron_nashor",
  label = h3("Number of baron nashor"),
  min = min_baron_nashor, max = max_baron_nashor, value = 0)

# sliderInput widget of dragon
min_dragon = 0
max_dragon = merge %>% drop_na(dragon) %>% distinct(dragon) %>% max()

sliderInput(
  "dragon",
  label = h3("Number of dragon (applied only before S6)"),
  min = min_dragon, max = max_dragon, value = 0)

# sliderInput widget of air dragon
min_air_dragon = 0
max_air_dragon = merge %>% drop_na(air_dragon) %>% distinct(air_dragon) %>% max()

sliderInput(
  "air_dragon",
  label = h3("Number of air dragon"),
  min = min_air_dragon, max = max_air_dragon, value = 0)

# sliderInput widget of earth dragon
min_earth_dragon = 0
max_earth_dragon = merge %>% drop_na(earth_dragon) %>% distinct(earth_dragon) %>% max()

sliderInput(
  "earth_dragon",
  label = h3("Number of earth dragon"),
  min = min_earth_dragon, max = max_earth_dragon, value = 0)

# sliderInput widget of water dragon
min_water_dragon = 0
max_water_dragon = merge %>% drop_na(water_dragon) %>% distinct(water_dragon) %>% max()

sliderInput(
  "water_dragon",
  label = h3("Number of water dragon"),
  min = min_water_dragon, max = max_water_dragon, value = 0)

# sliderInput widget of fire dragon
min_fire_dragon = 0
max_fire_dragon = merge %>% drop_na(fire_dragon) %>% distinct(fire_dragon) %>% max()

sliderInput(
  "fire_dragon",
  label = h3("Number of fire dragon"),
  min = min_fire_dragon, max = max_fire_dragon, value = 0)
```

Column {.tabset}
-----------------------------------------------------------------------

```{r}
renderPrint({
  p = exp(-1.237 + 0.00075*input[["gold_range"]] + 1.192*input[["baron_nashor"]] + 0.299*input[["dragon"]] + 0.288*input[["air_dragon"]] + 0.152*input[["earth_dragon"]] + 0.203*input[["water_dragon"]] + 0.606*input[["fire_dragon"]]) / 
    (1 + exp(-1.237 + 0.00075*input[["gold_range"]] + 1.192*input[["baron_nashor"]] + 0.299*input[["dragon"]] + 0.288*input[["air_dragon"]] + 0.152*input[["earth_dragon"]] + 0.203*input[["water_dragon"]] + 0.606*input[["fire_dragon"]]))
  p = p * 100
  prob = p %>% round(digits = 2) %>% paste("%") %>% as.character()
  prob = str_c("Your winning probability is ", prob)
  prob
})
```



